# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
#
$:.unshift File.join(File.dirname(__FILE__), '..', 'lib')
$:.unshift File.dirname(__FILE__)

require 'bundler/setup'
Bundler.require

require 'rspec'
# require 'webmock/rspec'
require 'pp'

begin # load pry if is available
require 'pry'
rescue LoadError
end

require 'vcr'
require 'timecop'

module Oddb2xml
  # we override here a few directories to make input/output when running specs to
  # be in different places compared when running
  SpecData       = File.join(File.dirname(__FILE__), 'data')
  WorkDir        = File.join(File.dirname(__FILE__), 'run')
  Downloads      = File.join(WorkDir, 'downloads')
  SpecCompressor = File.join(Oddb2xml::SpecData, 'compressor')
  GTINS_DRUGS = [ '733905577161',
                  '7680536620137',
                  '7680620690084', # needed for extractor_spec.rb
                  '7680555580054',
                  '7680316950157',
                  '5000223439507',
                  '5000223074777',
                  '4042809018288',
                  '4042809018400',
                  '4042809018493',
                  '7611600441013',
                  '7611600441020',
                  '7611600441037',
                  ]

  GTINS_MEDREG = [
    7601001380028, # Glarus
    7601002017145, # Kantonsspital Glarus AG
    7601001395145, # Kantonstierärztlicher Dienst
    7601001396043, # St. Fridolin Pharma AG
    7601000159199, #  Davatz  Ursula
    7601000159199, #  Davatz  Ursula
    7601000254344, #  Pfister Daniel  8753  Mollis
    7601000254207, #  Züst  Peter 8753  Mollis
    7601000752314, #  Züst  Yvonne  8753  Mollis
    ]

end

VCR.configure do |config|
  config.cassette_library_dir = "spec/fixtures/vcr_cassettes"
  config.hook_into :webmock # or :fakeweb
  config.debug_logger = File.open(File.join(File.dirname(File.dirname(__FILE__)), 'vcr.log'), 'w+')
  config.debug_logger.sync = true
  config.default_cassette_options = { :record => :new_episodes,
                                      :preserve_exact_body_bytes => true,
                                      # :match_requests_on => [:uri, :method, :body, :headers]
                                    }
  config.before_http_request(:real?) do |request|
    $stderr.puts("before real request: #{request.method} #{request.uri}")
    $stderr.flush
  end if false
end
VCR.use_cassette('oddb2xml') do |cassette|
  Timecop.freeze(cassette.originally_recorded_at || Time.now)
end if false
VCR.insert_cassette('oddb2xml')

AllCompositionLines = File.expand_path("#{__FILE__}/../data/compositions.txt")
AllColumn_C_Lines = File.expand_path("#{__FILE__}/../data/column_c.txt")

require 'oddb2xml'

module Kernel
  def buildr_capture(stream)
    begin
      stream = stream.to_s
      eval "$#{stream} = StringIO.new"
      yield
      result = eval("$#{stream}").string
    ensure
      eval "$#{stream} = #{stream.upcase}"
    end
    result
  end
end

module ServerMockHelper
  def cleanup_compressor
    [ File.join(Oddb2xml::SpecCompressor, '*.zip'),
      File.join(Oddb2xml::SpecCompressor, '*.tar.gz'),
      File.join(Oddb2xml::SpecCompressor, 'epha_interactions.txt*'),
      File.join(Oddb2xml::SpecCompressor, 'medregbm_company.txt*'),
      File.join(Oddb2xml::SpecCompressor, 'medregbm_person.txt*'),
      File.join(Oddb2xml::SpecCompressor, 'zurrose_transfer.dat.*'),
      File.join(Oddb2xml::SpecCompressor, 'oddb2xml_files_nonpharma.xls.*'),
      ].each { |file| FileUtils.rm_f(Dir.glob(file), :verbose => false) if Dir.glob(file).size > 0 }
  end
  def cleanup_directories_before_run
    dirs = [ Oddb2xml::Downloads, Oddb2xml::WorkDir]
    dirs.each{ |dir| FileUtils.rm_rf(Dir.glob(File.join(dir, '*')), :verbose => false) }
    dirs.each{ |dir| FileUtils.makedirs(dir, :verbose => false) }
    cleanup_compressor
  end
  
  def setup_server_mocks
    puts "Skip setup_server_mocks as we want to use vcr"
  end
end

RSpec.configure do |config|
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
  config.filter_run_excluding :slow
  #config.exclusion_filter = {:slow => true}

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'

  # Helper
  config.include(ServerMockHelper)
end
