name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    env:
      BUNDLE_PATH: ".bundle/gems"
      BUNDLE_WITHOUT: "debugger"
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ruby
        bundler-cache: true
    - run: |
        bundle exec rake gem
    - uses: ncipollo/release-action@v4
      with:
        allowUpdates: true
        artifacts: |
          pkg/*.gem
